---
global:
  smtp_smarthost: localhost:25
  smtp_from: alertmanager@localhost
route:
  group_by:
  - alertname
  - instance
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: slack
  routes:
  - receiver: slack
receivers:
- name: slack
  slack_configs:
  - api_url:
    channel: test-ali
    send_resolved: true
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
