version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_new
    ports:
    - 30090:9090
    command:
    - --config.file=/home/wradmin/docker-prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/home/wradmin/docker-prometheus/prometheus.yml:ro
    - ./rules.yml:/home/wradmin/docker-prometheus/rules.yml:ro
    depends_on:
    - cadvisor
  grafana:
    image: grafana/grafana
    container_name: grafana_new
    ports:
    - 3000:3000
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor_new
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
#    - /cgroup:/cgroup:ro #RHEL
    depends_on:
    - redis
    userns_mode: "host"
#    privileged: true #rhel
  redis:
    image: redis:latest
    container_name: redis_new
    ports:
    - 6379:6379
  redis_exporter:
    image: quay.io/oliver006/redis_exporter:latest
    container_name: redis_exporter_new
    ports:
    - 9121:9121
    command:
    - --redis.addr=10.1.11.75:6379
  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager_container
    ports:
    - 9093:9093
    command:
    - --config.file=/home/wradmin/docker-prometheus/alertmanager.yml
    volumes:
    - ./alertmanager.yml:/home/wradmin/docker-prometheus/alertmanager.yml:ro