#global config    
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
 # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'e3-monitor' #update depending on deployment node for reporting update
  
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090'] #point at what the POD is using, not the external port
      labels:
        alias: 'prometheus'
  
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080'] #point at what the POD is using
      labels:
        alias: 'cadvisor'
 
  - job_name: 'node_exporter'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['0.0.0.0:9100']
