#global config    
global:
 scrape_interval: 15s 
 evaluation_interval: 15s 
 # scrape_timeout is set to the global default (10s).
 
external_labels:
  monitor: 'e3-monitor' #update depending on deployment node for reporting update
  
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
      labels:
        alias: 'prometheus'
  
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8081']
      labels:
        alias: 'cadvisor'
 
  - job_name: 'docker'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9323']
